# Copyright 2016 Daniel Wilhelm
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: create compose service directory
  file: path={{ docker_service_directory }}/{{ docker_service.name }}
    mode=0755 state=directory

- name: place initial compose file for {{ docker_service.name }} on server
  template: src={{ docker_service.compose_file_startup|default(docker_service.compose_file) }}
    dest={{ docker_service_directory }}/{{ docker_service.name }}/docker-compose.yml
    validate='{{ docker_compose_bin_path }} -f %s config -q' force=no

- name: place systemd unit for {{ docker_service.name }} on server
  template: src=docker-service.service.j2
    dest={{ systemd_unit_path }}/{{ docker_service.systemd_service_name|default('docker-' + docker_service.name) }}.service

- name: include service specific config
  include: "{{ docker_compose_service.service_config }}"
  when: docker_service.service_config is defined

- name: enable and start {{ docker_service.systemd_service_name|default('docker-' + docker_service.name) }} service
  systemd: name={{ docker_service.systemd_service_name|default('docker-' + docker_service.name) }}
    daemon_reload=yes enabled=yes state=started

- name: place permanent compose file for {{ docker_service.name }} on server
  template: src={{ docker_service.compose_file }}
    dest={{ docker_service_directory }}/{{ docker_service.name }}/docker-compose.yml
    validate='{{ docker_compose_bin_path }} -f %s config -q'
